package cn.mazekkkk.product.dao.common;

import java.util.Date;

public class Gametrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.id
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.connectorNo
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String connectorno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.partnerId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String partnerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.gamesBoxId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String gamesboxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.gamesId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String gamesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.openId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.clubCardId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String clubcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.orderTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.payTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.payMode
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer paymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.tradeType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.tradeState
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer tradestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.tradeScene
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer tradescene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.payAmount
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer payamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.coin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.remainCoin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer remaincoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.gameTimes
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer gametimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.discountType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer discounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.discountId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private String discountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gametrade.discountAmt
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    private Integer discountamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.id
     *
     * @return the value of gametrade.id
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.id
     *
     * @param id the value for gametrade.id
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.connectorNo
     *
     * @return the value of gametrade.connectorNo
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getConnectorno() {
        return connectorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.connectorNo
     *
     * @param connectorno the value for gametrade.connectorNo
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setConnectorno(String connectorno) {
        this.connectorno = connectorno == null ? null : connectorno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.partnerId
     *
     * @return the value of gametrade.partnerId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getPartnerid() {
        return partnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.partnerId
     *
     * @param partnerid the value for gametrade.partnerId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setPartnerid(String partnerid) {
        this.partnerid = partnerid == null ? null : partnerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.gamesBoxId
     *
     * @return the value of gametrade.gamesBoxId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getGamesboxid() {
        return gamesboxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.gamesBoxId
     *
     * @param gamesboxid the value for gametrade.gamesBoxId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setGamesboxid(String gamesboxid) {
        this.gamesboxid = gamesboxid == null ? null : gamesboxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.gamesId
     *
     * @return the value of gametrade.gamesId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getGamesid() {
        return gamesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.gamesId
     *
     * @param gamesid the value for gametrade.gamesId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setGamesid(String gamesid) {
        this.gamesid = gamesid == null ? null : gamesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.openId
     *
     * @return the value of gametrade.openId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.openId
     *
     * @param openid the value for gametrade.openId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.clubCardId
     *
     * @return the value of gametrade.clubCardId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getClubcardid() {
        return clubcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.clubCardId
     *
     * @param clubcardid the value for gametrade.clubCardId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setClubcardid(String clubcardid) {
        this.clubcardid = clubcardid == null ? null : clubcardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.orderTime
     *
     * @return the value of gametrade.orderTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.orderTime
     *
     * @param ordertime the value for gametrade.orderTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.payTime
     *
     * @return the value of gametrade.payTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.payTime
     *
     * @param paytime the value for gametrade.payTime
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.payMode
     *
     * @return the value of gametrade.payMode
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getPaymode() {
        return paymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.payMode
     *
     * @param paymode the value for gametrade.payMode
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setPaymode(Integer paymode) {
        this.paymode = paymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.tradeType
     *
     * @return the value of gametrade.tradeType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getTradetype() {
        return tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.tradeType
     *
     * @param tradetype the value for gametrade.tradeType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setTradetype(Integer tradetype) {
        this.tradetype = tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.tradeState
     *
     * @return the value of gametrade.tradeState
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getTradestate() {
        return tradestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.tradeState
     *
     * @param tradestate the value for gametrade.tradeState
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setTradestate(Integer tradestate) {
        this.tradestate = tradestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.tradeScene
     *
     * @return the value of gametrade.tradeScene
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getTradescene() {
        return tradescene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.tradeScene
     *
     * @param tradescene the value for gametrade.tradeScene
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setTradescene(Integer tradescene) {
        this.tradescene = tradescene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.payAmount
     *
     * @return the value of gametrade.payAmount
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.payAmount
     *
     * @param payamount the value for gametrade.payAmount
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setPayamount(Integer payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.coin
     *
     * @return the value of gametrade.coin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.coin
     *
     * @param coin the value for gametrade.coin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.remainCoin
     *
     * @return the value of gametrade.remainCoin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getRemaincoin() {
        return remaincoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.remainCoin
     *
     * @param remaincoin the value for gametrade.remainCoin
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setRemaincoin(Integer remaincoin) {
        this.remaincoin = remaincoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.gameTimes
     *
     * @return the value of gametrade.gameTimes
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getGametimes() {
        return gametimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.gameTimes
     *
     * @param gametimes the value for gametrade.gameTimes
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setGametimes(Integer gametimes) {
        this.gametimes = gametimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.discountType
     *
     * @return the value of gametrade.discountType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getDiscounttype() {
        return discounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.discountType
     *
     * @param discounttype the value for gametrade.discountType
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setDiscounttype(Integer discounttype) {
        this.discounttype = discounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.discountId
     *
     * @return the value of gametrade.discountId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public String getDiscountid() {
        return discountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.discountId
     *
     * @param discountid the value for gametrade.discountId
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setDiscountid(String discountid) {
        this.discountid = discountid == null ? null : discountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gametrade.discountAmt
     *
     * @return the value of gametrade.discountAmt
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public Integer getDiscountamt() {
        return discountamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gametrade.discountAmt
     *
     * @param discountamt the value for gametrade.discountAmt
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    public void setDiscountamt(Integer discountamt) {
        this.discountamt = discountamt;
    }
}