package cn.mazekkkk.product.dao.common;

public class SRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.id
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.name
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.uid
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.id
     *
     * @return the value of s_role.id
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.id
     *
     * @param id the value for s_role.id
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.name
     *
     * @return the value of s_role.name
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.name
     *
     * @param name the value for s_role.name
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.uid
     *
     * @return the value of s_role.uid
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.uid
     *
     * @param uid the value for s_role.uid
     *
     * @mbggenerated Wed Jun 22 15:51:49 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}