package cn.mazekkkk.product.dao.common;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

public class SUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.name
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.dob
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private Date dob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.dob
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    private Set<SRole> SRole = new HashSet<>(0);

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.name
     *
     * @return the value of s_user.name
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.name
     *
     * @param name the value for s_user.name
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.dob
     *
     * @return the value of s_user.dob
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.dob
     *
     * @param dob the value for s_user.dob
     *
     * @mbggenerated Tue Jun 21 16:33:50 CST 2016
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    public Set<cn.mazekkkk.product.dao.common.SRole> getSRole() {
        return SRole;
    }

    public void setSRole(Set<cn.mazekkkk.product.dao.common.SRole> SRole) {
        this.SRole = SRole;
    }
}