package cn.mazekkkk.product.dao.mapper;

import cn.mazekkkk.product.dao.common.Gametrade;
import cn.mazekkkk.product.dao.common.GametradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GametradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int countByExample(GametradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int deleteByExample(GametradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int insert(Gametrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int insertSelective(Gametrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    List<Gametrade> selectByExample(GametradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    Gametrade selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") Gametrade record, @Param("example") GametradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int updateByExample(@Param("record") Gametrade record, @Param("example") GametradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int updateByPrimaryKeySelective(Gametrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gametrade
     *
     * @mbggenerated Wed Jan 18 18:25:47 CST 2017
     */
    int updateByPrimaryKey(Gametrade record);
}