package cn.mazekkkk.product.common;

import java.util.Date;

public class XncAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.region_id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.community
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.street
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.post_code
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xnc_address.add_time
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.id
     *
     * @return the value of xnc_address.id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.id
     *
     * @param id the value for xnc_address.id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.region_id
     *
     * @return the value of xnc_address.region_id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.region_id
     *
     * @param regionId the value for xnc_address.region_id
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.community
     *
     * @return the value of xnc_address.community
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.community
     *
     * @param community the value for xnc_address.community
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.street
     *
     * @return the value of xnc_address.street
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.street
     *
     * @param street the value for xnc_address.street
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.post_code
     *
     * @return the value of xnc_address.post_code
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.post_code
     *
     * @param postCode the value for xnc_address.post_code
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xnc_address.add_time
     *
     * @return the value of xnc_address.add_time
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xnc_address.add_time
     *
     * @param addTime the value for xnc_address.add_time
     *
     * @mbggenerated Wed Feb 03 16:15:00 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}